version: '3'
services:
  keycloak:
    container_name: keycloak
    image: jboss/keycloak
    environment:
      - KEYCLOAK_USER=kadmin
      - KEYCLOAK_PASSWORD=Kadm1234
    ports:
      - "8080:8080"
  openldap:
    container_name: openldap
    image: osixia/openldap:1.3.0
    environment:
      - LDAP_ORGANISATION=The Corporation
      - LDAP_DOMAIN=corp.com
      - LDAP_ADMIN_PASSWORD=Ladm1234
    ports:
      - "389:389"